### ISSUE TITLE
How to get it running in a chroot

### ISSUE THREAD

**Issue by Ijdtm7** [JJTech0130/MultiMC5#36]
System Information
-----------------------------
MultiMC version: 0.6.12-CUSTOM(your latest arm 64 build)

Operating System:aarch64 debian in a chroot

Summary of the issue or suggestion:
----------------------------------------------
So after getting frustrated with manjaro and corrupting my sd card. I went back to Raspbian. I am using a 64 bit chroot that changes me from arm32 raspbian to arm64 debian. However when i launch my 1.12.2 instance it crashes when launching. I am trying to use the arm64 version since ive heard arm32 is as slow as manjaro

What should happen:
------------------------------
1.12.2 should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.go in a debian chroot

2.install jdk 8 arm 64 from oracle

3.open multimc and launch 1.12.2

Suspected cause:
---------------------------
It seems to be an issue with lwjgl, like always

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/oASCt

Additional Info:
---------------------------
i am using jdk8 from oracle since openjdk 8 was removed from the repo

**Comment by Ijdtm7** [comment]
I think i see something with that java version. It says its 32 bit in the logs but i grabbed the 64 bit one and put it in that exact folder

**Comment by Ijdtm7** [comment]
UPDATE: i managed to get openjdk-8-jdk from the debian unstable repo. the crash log has now changed when running the game: https://paste.ee/p/0KvcR

**Comment by JJTech0130** [comment]
I would use 64 bit raspbian, the chroot may not work with opengl. Never tried it. I also got frustrated with Manjaro after I realized it does not have libc++11, which I need for the application I am developing. It is also slow :). I now use ARM 64 bit Kali as it has more packages (including OpenJDK8 and a newer version of Qt5). Here is a video of how fast it launches Minecraft 1.16.1 without being overclocked 
[launching_minecraft_1.16.mp4.zip](https://github.com/JJTech0130/MultiMC5/files/5002402/launching_minecraft_1.16.mp4.zip)

**Comment by JJTech0130** [comment]
you could also try installing `xrandr` in the chroot as it helped with the `no OpenGl context` error in the past.

**Comment by Ijdtm7** [comment]
I’ll try to see if i can mess around with it. I can’t use raspbian 64 bit because I’m using the supreme pro RetroPie image. It does run dolphin the Wii and GameCube emulator which might use OpenGL I’m not sure. I’ll install xrandr and see. The error looked like it changed tho once I installed openjdk instead of Oracle. I can’t tell is it still something with OpenGL?

**Comment by Ijdtm7** [comment]
Oops accidentally closed the buttons are too close

**Comment by Ijdtm7** [comment]
Ok @JJTech0130 is awesome and figured out the issue pretty quickly. For future reference heres how to run this in a aarch64 debian chroot. The reason i did this is cause the 32 bit version is slow but note you still will probably need to install optifine or sodium etc. So first you need openjdk 8, this is not in the main debian repo. so add this in your /etc/apt/sources.list:`deb [allow-insecure=yes] http://ftp.us.debian.org/debian sid main` this will give the access to the experimental repo. now do `sudo apt-get install openjdk-8-jdk` Now in order for minecraft to launch, we need xrandr. do `sudo apt-get install x11-xserver-utils`
now grab the arm64 version of multimc and enjoy! tested with 1.16.1 and 1.12.2

**Comment by JJTech0130** [comment]
Yup. You could also install openjdk from https://adoptopenjdk.net/ because its not such a good idea to use debian sid, however you are is a chroot so I guess it doesn't matter.

Closing as solved

**Comment by techtimefor** [comment]
libc++ is avalible for manjaro  through the aur https://aur.archlinux.org/packages/libc%2B%2B/
Make sure to edit the PKGBUILD and change `arch=('i686' 'x86_64')` to `arch=('aarch64')`

How to install
1. `git clone https://aur.archlinux.org/libc++.git`
2. `cd libc++`
3. `makepkg -si`
It should build and install hope this helps
