### ISSUE TITLE
Missing Meta Versions

### ISSUE THREAD

**Issue by Virusnest** [JJTech0130/MultiMC5#65]
The MultiMC meta-database is outdated and needs updating!

you can't use the latest version of Minecraft without some finicky workarounds

if you have discontinued the Metabase can you please point me to the code for the version grabber so I can fix it myself

**Comment by agarleanu** [comment]
I second this. It's understandable to not be able to update it at the moment, and if that's the case, could you make a small guide in README update so we can PR the updates in the future?

**Comment by Virusnest** [comment]
Yes I have noticed that you can add a custom meta for the build config but if I use the official MultiMC one I can't get the Linux arm LWJGL
I may be able to make my own repo but it will be tempory

**Comment by JJTech0130** [comment]
I will see what I can do when I get time.

**Comment by JJTech0130** [comment]
Unfortunately, I am very busy. For now, the best way get the official meta repo, and replace the LWJGL and LWJGL3 folders with mine.

**Comment by Virusnest** [comment]
ok thx
