### ISSUE TITLE
mac m1 arm64

### ISSUE THREAD

**Issue by abasgames** [JJTech0130/MultiMC5#98]
is it possible to support it ?

**Comment by JJTech0130** [comment]
Possibly? I have no mac to test it on. You could try to get it to work. I won't be able to do anything until summer. Lots of school finals.

**Comment by JJTech0130** [comment]
Look into this: 
https://github.com/yusefnapora/m1-multimc-hack

**Comment by JJTech0130** [comment]
I don't have a Mac, so I can't test anything. You can try the link, hopefully that is helpful. Closing as there's not much I can do.
